kind: pipeline
type: exec
name: Build all hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: Show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata
- name: Run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace
- name: Build python-escpos
  commands:
  - nix build -v -L '.#python-escpos'
  - whoami
  - echo $AWS_SECRET_ACCESS_KEY
  - echo $AWS_ACCESS_KEY_ID
  - nix copy --to 's3://example-nix-cache?profile=default&scheme=https&region=eu-central-1&endpoint=s3.lounge.rocks' $(nix-store -qR result/) -L -vvv
- name: Build photobooth-app
  commands:
  - nix build -v -L '.#photobooth-app'
- name: Build sd-card image
  commands:
  - nix build -v -L '.#raspi-image'
